### ISSUE TITLE
[BUG] Toast Message - Showing placeholder text

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.SugarLearning#18] opened 2020-07-27 02:49 UTC
cc: @adamcogan 

When I save a SugarLearning item, the success toast message shows placeholder text instead of a meaningful message.

![CleanShot 2020-07-27 at 12 38 11](https://user-images.githubusercontent.com/600044/88498824-8ef52380-d007-11ea-92e3-464588ac308d.png)
**Figure: Toast should show something human understandable**

**Comment by christoment** [comment] 2020-07-29 00:02
Hi @wicksipedia , this is now fixed 😊

The issue is that there's a mispelling in the translation name (`sucess` instead of `success`).
![image](https://user-images.githubusercontent.com/35278147/88741179-5168d580-d182-11ea-8250-b28d9b174687.png)

This fix is now live in production.

**Closed by christoment** 2020-07-29 00:02 UTC
Labels: bug
