### ISSUE TITLE
Cant log in via google account

### ISSUE THREAD

**Issue by william-liebenberg** [SSWConsulting/SSW.SugarLearning#16] opened 2020-07-27 01:30 UTC
Logged in via google auth,
Entered my name and lastname to register, then got an error:

URL: https://my.sugarlearning.com/Public/ExternalAccount/ExternalLoginConfirmation?LoginProvider=Google&CompanyId=0&FullName=%20&UserName=awie.liebenberg%40gmail.com

![image](https://user-images.githubusercontent.com/23464439/88495148-60258000-cffc-11ea-8ee1-76263ce5acff.png)
Figure: Error page after registering

**Comment by christoment** [comment] 2020-07-29 00:09
Tracking this on AB#55244

**Comment by christoment** [comment] 2020-07-30 04:25
I can reproduce this error and it looks like a constraint error was thrown while trying to create a new user in the database.
This is due to an existing record with the same generated `userId` already exists and user creation from external account flow did not try to find a unique user ID.

AB#55244 has been merged and deployed, and it fixed this bug.
The fix is to make sure that creating a user via external account will generate a unique user, falling back to an indexed user name incrementally (e.g. if `bob_northwind` exists, it should generate `bob_northwind_1`, `bob_northwind_2`, ...).
(P.S. this is what is actually being done on the normal registration process. Somehow external account registration follows a different pathway).

I'm closing this issue since I can't see the issue again after merging the fix.
Please let me know and re-open the ticket if you're still facing the same issue @william-liebenberg . 😊

**Closed by christoment** 2020-07-30 04:25 UTC
Labels: bug
